### ISSUE TITLE
Version Comparer doesn't treat null in version numbers as a wildcard

### ISSUE THREAD

**Issue by STeeL835** [Ruhrpottpatriot/SemanticVersion#14]
SemanticVersion allows wildcards, but currently this has no usage as CompareTo thinks of a null (which is meant to be a wildcard) as a lower number than 0

```cs
SemanticVersion left = "1.0.0"; 
SemanticVersion right = "1.0.*";

Console.WriteLine(left.Equals(right)); // False
Console.WriteLine(left.CompareTo(right)); // 1
```

I think this can be resolved by changing condition here:
https://github.com/Ruhrpottpatriot/SemanticVersion/blob/7ddf1b54f8f2129eadb1e326c8a458a3df71c72e/src/SemanticVersion/Utilities.cs#L15-L22
to 
```cs
if (left is null || right is null) return 0;
return left.Value.CompareTo(right.Value)
```

I'd like to help with this issue by creating a PR for this change if there are no objections

**Comment by Ruhrpottpatriot** [comment]
Sure, go ahead. You don't need my permission to open a PR.

**Comment by STeeL835** [comment]
I created the PR. I also changed the Prerelease comparer to treat '*' as a wildcard (and renamed parameters as in Utilities method). 
However I'm concerned about initializing the version object:
* Parsing from string doesn't read a full version if it sees a wildcard. For example, it will parse `2.*.3` as `2.*.*` which is reasonable from the Standard point of view, but can be unexpected from code point of view
* It is possible to instantiate `2.*.3` from constructor manually, but it doesn't have any checks - potentially I can make a version with negative numbers and zalgo in Prerelease, which will not be by the standard

I can add checks, but the question is: should it allow wildcards in the middle or it should throw an exception on constructing/casting? 
Also I can add a `IsStrict` or `HasWildcards` property and change `IsVersion` to allow users to know what they are dealing with (a version with wildcards or w/o), what do you think?

**Comment by Ruhrpottpatriot** [comment]
I'd be more inclined to stick to the standard as close as possible for now, since any programmer that actually uses the library should know and adhere to the standard anyway.
If there's really need to support versions such as `2.*.3` another PR (or me) could later add a "loosened" version, although I currently don't see any reason why you'd even need to select a version with a fixed patch, but wildcard minor. Really the only thing I could think of is a piece of software that would indicate backported patches/fixes that way.
